version: '3.8'

volumes:
  neo4j-data:

services:

  #
  # NGINX is probably overkill for now: Neo4j is potentially
  # self-sufficient for our use cases, especially after future SSL hardening
  #  nginx:
  #    image: nginx:latest
  #    ports:
  #      - 80:80
  #      - 443:443
  #    # volumes:
  #    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #    depends_on:
  #      - neo4j

  neo4j:
    image: us-central1-docker.pkg.dev/monarch-initiative/monarch-api/monarch-neo4j:4.4
    build: .
    env_file:
      - .env
    ports:
      - 7474:7474  # http
      - 7687:7687  # bolt
    volumes:
      - neo4j-data:/data
      - ./plugins:/plugins
      - ./dumps:/dumps
    # NEO4J_DUMP_FILENAME can be defined within the .env file
    # (in fact, it needs to be defined for this file to parse, e.g. to use
    # `docker compose build` or any other compose command)
    entrypoint: /scripts/load_and_boot_neo4j.sh $NEO4J_DUMP_FILENAME
